// <auto-generated />
using System;
using MedSim.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MedSim.Infrastructure.Migrations
{
    [DbContext(typeof(MedSimDbContext))]
    [Migration("20260817110907_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MedSim.Domain.Entities.CaseOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseStageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CaseStageId");

                    b.ToTable("CaseOptions");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.CaseStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MedicalCaseId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MedicalCaseId");

                    b.ToTable("CaseStages");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.MedicalCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("InitialText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsProcedural")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("MedicalCases");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.SolvedCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("EarnedPoints")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSolved")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MedicalCaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MedicalCaseId");

                    b.HasIndex("UserId");

                    b.ToTable("SolvedCases");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Nickname")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.CaseOption", b =>
                {
                    b.HasOne("MedSim.Domain.Entities.CaseStage", "CaseStage")
                        .WithMany("Options")
                        .HasForeignKey("CaseStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaseStage");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.CaseStage", b =>
                {
                    b.HasOne("MedSim.Domain.Entities.MedicalCase", "MedicalCase")
                        .WithMany("Stages")
                        .HasForeignKey("MedicalCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalCase");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.MedicalCase", b =>
                {
                    b.HasOne("MedSim.Domain.Entities.Department", "Department")
                        .WithMany("Cases")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.SolvedCase", b =>
                {
                    b.HasOne("MedSim.Domain.Entities.MedicalCase", "MedicalCase")
                        .WithMany()
                        .HasForeignKey("MedicalCaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedSim.Domain.Entities.User", "User")
                        .WithMany("SolvedCases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalCase");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.CaseStage", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.Department", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.MedicalCase", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.User", b =>
                {
                    b.Navigation("SolvedCases");
                });
#pragma warning restore 612, 618
        }
    }
}
