// <auto-generated />
using System;
using MedSim.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MedSim.Infrastructure.Migrations
{
    [DbContext(typeof(MedSimDbContext))]
    [Migration("20260820123901_AddTusClassicSystem")]
    partial class AddTusClassicSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MedSim.Domain.Entities.CaseOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseStageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CaseStageId");

                    b.ToTable("CaseOptions");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.CaseStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MedicalCaseId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MedicalCaseId");

                    b.ToTable("CaseStages");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.MedicalCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DifficultyReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DifficultyScore")
                        .HasColumnType("integer");

                    b.Property<string>("InitialText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsProcedural")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("SubTopicId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SubTopicId");

                    b.ToTable("MedicalCases");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.SolvedCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("EarnedPoints")
                        .HasColumnType("integer");

                    b.Property<string>("GivenAnswers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSolved")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MedicalCaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MedicalCaseId");

                    b.HasIndex("UserId");

                    b.ToTable("SolvedCases");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.SubTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("SubTopics");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.TusKnowledge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("ImportanceScore")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("KnowledgeText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RepetitionFrequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sources")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SubTopicId")
                        .HasColumnType("uuid");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SubTopicId");

                    b.ToTable("TusKnowledges");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.TusKnowledgeProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer");

                    b.Property<int>("IntervalDays")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NextReviewAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TusKnowledgeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Views")
                        .HasColumnType("integer");

                    b.Property<int>("WrongCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TusKnowledgeId");

                    b.HasIndex("UserId", "TusKnowledgeId")
                        .IsUnique();

                    b.ToTable("TusKnowledgeProgresses");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.TusQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrectOption")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DifficultyReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DifficultyScore")
                        .HasColumnType("integer");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsClassic")
                        .HasColumnType("boolean");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OptionE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SubTopicId")
                        .HasColumnType("uuid");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TusKnowledgeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SubTopicId");

                    b.HasIndex("TusKnowledgeId");

                    b.ToTable("TusQuestions");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.TusSolvedQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<string>("SelectedOption")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TusQuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TusQuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("TusSolvedQuestions");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Nickname")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.UserFriend", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FriendId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "FriendId");

                    b.HasIndex("FriendId");

                    b.ToTable("UserFriends");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.CaseOption", b =>
                {
                    b.HasOne("MedSim.Domain.Entities.CaseStage", "CaseStage")
                        .WithMany("Options")
                        .HasForeignKey("CaseStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaseStage");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.CaseStage", b =>
                {
                    b.HasOne("MedSim.Domain.Entities.MedicalCase", "MedicalCase")
                        .WithMany("Stages")
                        .HasForeignKey("MedicalCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalCase");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.MedicalCase", b =>
                {
                    b.HasOne("MedSim.Domain.Entities.Department", "Department")
                        .WithMany("Cases")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedSim.Domain.Entities.SubTopic", "SubTopic")
                        .WithMany("MedicalCases")
                        .HasForeignKey("SubTopicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");

                    b.Navigation("SubTopic");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.SolvedCase", b =>
                {
                    b.HasOne("MedSim.Domain.Entities.MedicalCase", "MedicalCase")
                        .WithMany()
                        .HasForeignKey("MedicalCaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedSim.Domain.Entities.User", "User")
                        .WithMany("SolvedCases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalCase");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.SubTopic", b =>
                {
                    b.HasOne("MedSim.Domain.Entities.Topic", "Topic")
                        .WithMany("SubTopics")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.Topic", b =>
                {
                    b.HasOne("MedSim.Domain.Entities.Department", "Department")
                        .WithMany("Topics")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.TusKnowledge", b =>
                {
                    b.HasOne("MedSim.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MedSim.Domain.Entities.SubTopic", "SubTopic")
                        .WithMany()
                        .HasForeignKey("SubTopicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");

                    b.Navigation("SubTopic");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.TusKnowledgeProgress", b =>
                {
                    b.HasOne("MedSim.Domain.Entities.TusKnowledge", "TusKnowledge")
                        .WithMany()
                        .HasForeignKey("TusKnowledgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedSim.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TusKnowledge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.TusQuestion", b =>
                {
                    b.HasOne("MedSim.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("MedSim.Domain.Entities.SubTopic", "SubTopic")
                        .WithMany("TusQuestions")
                        .HasForeignKey("SubTopicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MedSim.Domain.Entities.TusKnowledge", "TusKnowledge")
                        .WithMany("Questions")
                        .HasForeignKey("TusKnowledgeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");

                    b.Navigation("SubTopic");

                    b.Navigation("TusKnowledge");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.TusSolvedQuestion", b =>
                {
                    b.HasOne("MedSim.Domain.Entities.TusQuestion", "TusQuestion")
                        .WithMany()
                        .HasForeignKey("TusQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedSim.Domain.Entities.User", "User")
                        .WithMany("TusSolvedQuestions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TusQuestion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.UserFriend", b =>
                {
                    b.HasOne("MedSim.Domain.Entities.User", "Friend")
                        .WithMany()
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedSim.Domain.Entities.User", "User")
                        .WithMany("Friends")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Friend");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.CaseStage", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.Department", b =>
                {
                    b.Navigation("Cases");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.MedicalCase", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.SubTopic", b =>
                {
                    b.Navigation("MedicalCases");

                    b.Navigation("TusQuestions");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.Topic", b =>
                {
                    b.Navigation("SubTopics");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.TusKnowledge", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("MedSim.Domain.Entities.User", b =>
                {
                    b.Navigation("Friends");

                    b.Navigation("SolvedCases");

                    b.Navigation("TusSolvedQuestions");
                });
#pragma warning restore 612, 618
        }
    }
}
